ALTER TABLE Schueler ADD FOREIGN KEY (Klasse) REFERENCES Klasse(KlasseID) ON DELETE CASCADE;

ALTER TABLE Klasse ADD FOREIGN KEY (istKlassenlehrer) REFERENCES Lehrer(LehrerID) ON DELETE CASCADE;

ALTER TABLE Klasse ADD FOREIGN KEY (istKlassensprecher) REFERENCES Schueler(SchuelerID) ON DELETE CASCADE;

ALTER TABLE Checkliste ADD FOREIGN KEY (Lehrer) REFERENCES Lehrer(LehrerID) ON DELETE CASCADE;

ALTER TABLE Checkliste ADD FOREIGN KEY (Klasse) REFERENCES Klasse(KlasseID) ON DELETE CASCADE;

ALTER TABLE Checklisteneintrag ADD FOREIGN KEY (Schueler) REFERENCES Schueler(SchuelerID) ON DELETE CASCADE;

ALTER TABLE Checklisteneintrag ADD FOREIGN KEY (Checkliste) REFERENCES Checkliste(ChecklisteID) ON DELETE CASCADE;
